package main
    
import (
	"github.com/gin-gonic/gin"
	_ "github.com/jinzhu/gorm/dialects/mysql"
)

func main() {
	r := gin.Default()
	r.Use(BeforeRequest())
	v1 := r.Group("/api/v1/oee")
	{
		v1.GET("/device/:id",fetchSingleDevice)
		v1.POST("/device/",createDevice)
		v1.PUT("/device/:id",updateDevice)
		v1.DELETE("/device/:id",deleteDevice)
		v1.POST("/device/list",fetchPageDevice)
		v1.GET("/worktime/:id",fetchSingleWorktime)
		v1.POST("/worktime/",createWorktime)
		v1.PUT("/worktime/:id",updateWorktime)
		v1.DELETE("/worktime/:id",deleteWorktime)
		v1.POST("/worktime/list",fetchPageWorktime)
		v1.GET("/devicestatu/:id",fetchSingleDevicestatu)
		v1.POST("/devicestatu/",createDevicestatu)
		v1.PUT("/devicestatu/:id",updateDevicestatu)
		v1.DELETE("/devicestatu/:id",deleteDevicestatu)
		v1.POST("/devicestatu/list",fetchPageDevicestatu)
		v1.GET("/valvetime/:id",fetchSingleValvetime)
		v1.POST("/valvetime/",createValvetime)
		v1.PUT("/valvetime/:id",updateValvetime)
		v1.DELETE("/valvetime/:id",deleteValvetime)
		v1.POST("/valvetime/list",fetchPageValvetime)
		v1.GET("/valvetype/:id",fetchSingleValvetype)
		v1.POST("/valvetype/",createValvetype)
		v1.PUT("/valvetype/:id",updateValvetype)
		v1.DELETE("/valvetype/:id",deleteValvetype)
		v1.POST("/valvetype/list",fetchPageValvetype)
		v1.GET("/valve/:id",fetchSingleValve)
		v1.POST("/valve/",createValve)
		v1.PUT("/valve/:id",updateValve)
		v1.DELETE("/valve/:id",deleteValve)
		v1.POST("/valve/list",fetchPageValve)
		v1.GET("/bug/:id",fetchSingleBug)
		v1.POST("/bug/",createBug)
		v1.PUT("/bug/:id",updateBug)
		v1.DELETE("/bug/:id",deleteBug)
		v1.POST("/bug/list",fetchPageBug)
		v1.GET("/bugtype/:id",fetchSingleBugtype)
		v1.POST("/bugtype/",createBugtype)
		v1.PUT("/bugtype/:id",updateBugtype)
		v1.DELETE("/bugtype/:id",deleteBugtype)
		v1.POST("/bugtype/list",fetchPageBugtype)
		v1.GET("/alarmtype/:id",fetchSingleAlarmtype)
		v1.POST("/alarmtype/",createAlarmtype)
		v1.PUT("/alarmtype/:id",updateAlarmtype)
		v1.DELETE("/alarmtype/:id",deleteAlarmtype)
		v1.POST("/alarmtype/list",fetchPageAlarmtype)
		v1.GET("/alarm/:id",fetchSingleAlarm)
		v1.POST("/alarm/",createAlarm)
		v1.PUT("/alarm/:id",updateAlarm)
		v1.DELETE("/alarm/:id",deleteAlarm)
		v1.POST("/alarm/list",fetchPageAlarm)
		v1.GET("/project/:id",fetchSingleProject)
		v1.POST("/project/",createProject)
		v1.PUT("/project/:id",updateProject)
		v1.DELETE("/project/:id",deleteProject)
		v1.POST("/project/list",fetchPageProject)
		v1.GET("/plan/:id",fetchSinglePlan)
		v1.POST("/plan/",createPlan)
		v1.PUT("/plan/:id",updatePlan)
		v1.DELETE("/plan/:id",deletePlan)
		v1.POST("/plan/list",fetchPagePlan)
		v1.GET("/message/:id",fetchSingleMessage)
		v1.POST("/message/",createMessage)
		v1.PUT("/message/:id",updateMessage)
		v1.DELETE("/message/:id",deleteMessage)
		v1.POST("/message/list",fetchPageMessage)
	}
	r.Run("localhost:20303")
}
